import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Shield, AlertTriangle, CheckCircle, XCircle } from 'lucide-react';

const ContentPolicy: React.FC = () => {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto px-6 py-8 max-w-4xl">
        <div className="mb-6">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-primary hover:text-primary/80 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Billboard
          </Link>
        </div>

        <div className="bg-card border border-border rounded-lg p-8">
          <div className="flex items-center gap-3 mb-6">
            <Shield className="w-8 h-8 text-primary" />
            <h1 className="text-3xl font-bold">Content Policy</h1>
          </div>

          <div className="prose prose-gray dark:prose-invert max-w-none text-card-foreground">
            <p className="text-lg mb-6 text-card-foreground">
              The Million Slots AI Billboard requires all content to be AI-generated. This policy ensures 
              ethical, legal, and appropriate content for our digital canvas.
            </p>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
                <CheckCircle className="w-6 h-6 text-green-500" />
                Acceptable Content
              </h2>
              <ul className="space-y-2">
                <li>✅ AI-generated videos from legitimate AI tools (MidJourney, DALL-E, Stable Diffusion, etc.)</li>
                <li>✅ Original AI-created animations and motion graphics</li>
                <li>✅ AI-generated art, patterns, and abstract content</li>
                <li>✅ Educational or informational AI content</li>
                <li>✅ Creative AI-generated storytelling</li>
                <li>✅ AI-generated music videos and sound visualizations</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
                <XCircle className="w-6 h-6 text-red-500" />
                Prohibited Content
              </h2>
              <ul className="space-y-2">
                <li>❌ Real footage of people, places, or events</li>
                <li>❌ Copyrighted material not generated by AI</li>
                <li>❌ Explicit sexual or adult content</li>
                <li>❌ Violence, hate speech, or harmful content</li>
                <li>❌ Misleading deepfakes or deceptive content</li>
                <li>❌ Content promoting illegal activities</li>
                <li>❌ Spam or repetitive low-quality content</li>
                <li>❌ Political propaganda or misinformation</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
                <AlertTriangle className="w-6 h-6 text-yellow-500" />
                Content Verification
              </h2>
              <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4">
                <p className="mb-4 text-gray-800 dark:text-gray-200">
                  All uploaded content undergoes review to ensure compliance with our AI-only policy:
                </p>
                <ul className="space-y-2 text-gray-800 dark:text-gray-200">
                  <li>• Manual review by our moderation team</li>
                  <li>• AI detection tools to verify content origin</li>
                  <li>• Community reporting system</li>
                  <li>• Regular audits of live content</li>
                </ul>
              </div>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">Enforcement & Appeals</h2>
              <p className="mb-4">
                Content that violates this policy will be rejected with a full refund. For approved content 
                later found in violation, it will be removed from the billboard.
              </p>
              <p>
                If you believe your content was incorrectly rejected, you may appeal the decision by 
                contacting our support team with evidence of AI generation.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold mb-4">AI Tools We Accept</h2>
              <div className="grid md:grid-cols-2 gap-4">
                <div>
                  <h3 className="font-semibold mb-2">Video Generation:</h3>
                  <ul className="text-sm space-y-1">
                    <li>• RunwayML</li>
                    <li>• Pika Labs</li>
                    <li>• Stable Video Diffusion</li>
                    <li>• Synthesia</li>
                    <li>• Luma AI</li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-semibold mb-2">Image Generation:</h3>
                  <ul className="text-sm space-y-1">
                    <li>• MidJourney</li>
                    <li>• DALL-E</li>
                    <li>• Stable Diffusion</li>
                    <li>• Adobe Firefly</li>
                    <li>• Leonardo AI</li>
                  </ul>
                </div>
              </div>
            </section>

            <div className="bg-primary/10 border border-primary/20 rounded-lg p-6">
              <h3 className="font-semibold mb-2 text-card-foreground">Questions about Content Policy?</h3>
              <p className="text-sm text-card-foreground">
                Contact our team at admin@millionslotsai.com for clarification on acceptable content 
                or to report policy violations.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContentPolicy;