// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awgqhfaojevudjkhfibw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Z3FoZmFvamV2dWRqa2hmaWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDgzOTUsImV4cCI6MjA2ODE4NDM5NX0.kp_vJp-0weGEhC1dlavmpTrr3joCBaXvjoa59sbmcAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});